spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png
file.path: F:\BLOGS\2020-6-17-final\2020-6-17-final\BLOGS\src\main\resources\static\images\
